<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>JSDoc: Source: database/postgREST/diner.js</title>

    <script src="scripts/prettify/prettify.js"> </script>
    <script src="scripts/prettify/lang-css.js"> </script>
    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link type="text/css" rel="stylesheet" href="styles/prettify-tomorrow.css">
    <link type="text/css" rel="stylesheet" href="styles/jsdoc-default.css">
</head>

<body>

<div id="main">

    <h1 class="page-title">Source: database/postgREST/diner.js</h1>

    



    
    <section>
        <article>
            <pre class="prettyprint source linenums"><code>const axios = require('axios');

module.exports = {
    /**
     * byParam(key,value);
     * Request to an external service to consult an especific diner
     * 
     * @param {*} key Field to consult
     * @param {*} value Value of the especified column
     * @returns Returns a promise, if the key value matches with a row's field in DB, it will return an object with the diner found
     *          if there are no matches it will return an empty object
     *          if there is an error it will return an error object
     */
    byParam: (key, value) => {
        try {
            return axios.get(process.env.POSTGRES_URL + `/diners?${key}=eq.${value}&amp;limit=1000`)
                .then((res) => { return res.data })
                .catch((error) => [{
                    error: error.message,
                    trace: error.stack,
                    method: error.config.method,
                    url: error.config.url,
                    msg: 'Query error: ' + error.response.data.message
                }])
        } catch (error) {
            return [{
                error: error.msg,
                trace: error.trace,
                msg: 'Error in execution'
            }]
        }
    },
    /**
     * all();
     * Request to an external service to consult all existing diners
     * 
     * @returns Returns a promise, if the request is succesful returns an object with all diners data
     *          if there is an error in the request it will return an error object
     */
    all: () => {
        try {
            return axios.get(process.env.POSTGRES_URL + `/diners`)
                .then((res) => { return res.data })
                .catch((error) => [{
                    error: error.message,
                    trace: error.stack,
                    method: error.config.method,
                    url: error.config.url,
                    msg: 'Query error: ' + error.response.data.message
                }])
        } catch (error) {
            return [{
                error: error.msg,
                trace: error.trace,
                msg: 'Error in execution'
            }]
        }
    },
    /**
     * update(input);
     * Request to an external service to update a diner data
     * WARNING: DOESN'T WORKS CAN NOT FIND THE DINER TO UPDATE
     * @param {*} input object with update diner data
     * @returns Returns a promise, if the request is succesful returns an object with the updated diner data
     *          if there is an error in the request it will return an error object
     */
    update: (input) => {
        try {
            const {
                email,
                password,
                first_name,
                last_name,
                nickname,
                avatar,
                phone_number
            } = input;
            return axios({
                    method: 'PATCH',
                    url: process.env.POSTGRES_URL + '/auth_diner',
                    headers: {
                        Prefer: 'return=representation',
                    },
                    data: {
                        email,
                        password,
                        first_name,
                        last_name,
                        nickname,
                        avatar,
                        phone_number
                    }
                })
                .then((res) => { return res.data })
                .catch((error) => [{
                    error: error.message,
                    trace: error.stack,
                    method: error.config.method,
                    url: error.config.url,
                    msg: 'Query error: ' + error.response.data.message
                }]);
        } catch (error) {
            return [{
                error: error.msg,
                trace: error.trace,
                msg: 'Error in execution'
            }]
        }
    },
    /**
     * create(input);
     * Request to an external service to create a new diner
     *
     * @param {*} input object with new diner data
     * @returns Returns a promise, if the request is succesful returns an object with the new diner data
     *          if there is an error in the request it will return an error object
     */
    create: (input) => {
        const {
            email,
            password,
            first_name,
            last_name,
            nickname,
            avatar,
            phone_number
        } = input;
        try {
            return axios({
                    method: 'POST',
                    url: process.env.POSTGRES_URL + '/auth_diner',
                    headers: {
                        Prefer: 'return=representation',
                    },
                    data: {
                        email,
                        password,
                        first_name,
                        last_name,
                        nickname,
                        avatar,
                        phone_number
                    }
                })
                .then((res) => { return res.data })
                .catch((error) => [{
                    error: error.message,
                    trace: error.stack,
                    method: error.config.method,
                    url: error.config.url,
                    msg: 'Query error: ' + error.response.data.message
                }]);
        } catch (error) {
            return [{
                error: error.msg,
                trace: error.trace,
                msg: 'Error in execution'
            }]
        }
    }
};</code></pre>
        </article>
    </section>




</div>

<nav>
    <h2><a href="index.html">Home</a></h2><h3>Global</h3><ul><li><a href="global.html#allowedOrigins">allowedOrigins</a></li><li><a href="global.html#isProduction">isProduction</a></li><li><a href="global.html#limiter">limiter</a></li><li><a href="global.html#logFormat">logFormat</a></li><li><a href="global.html#max">max</a></li></ul>
</nav>

<br class="clear">

<footer>
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc 3.6.3</a> on Sun Sep 01 2019 16:15:05 GMT-0400 (GMT-04:00)
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
</body>
</html>
